### PR TITLE
Sykhro's work on the MP2k format

### PR DESCRIPTION
**Pull request by mikelow**
The only changes made were to remove a couple calls to gsl::narrow_cast<>(), since we removed the gsl-lite lib.

I figure you don't need to review your own code, just putting this up in case you want a last pass. Feel free to force-push over this branch to take credit for your work. As-is, I used "Co-authored" in the commit message.

### CODE REVIEW

**Review by sykhro — COMMENTED** [review]
IIRC this is not complete, but we can figure out what is missing later on :) let's get everything we can get out of that branch at this point

**Comment by mikelow** [comment]
> IIRC this is not complete, but we can figure out what is missing later on :) let's get everything we can get out of that branch at this point

Agreed. And also, "complete" was never the bar to merge format code :).

**Comment by mikelow** [comment]
@sykhro I feel remiss for not saying awesome job on this!

**Comment by mikelow** [comment]
I just send out a request to connect on linkedin, for lack of other reliable option. I'll send you my email when we connect (I can't send messages until then - ha).

**Pull request merged**
