### PR TITLE
Organize format code files into subdirectories

### PR DESCRIPTION
**Pull request by mikelow**
## Description
Organize the format-specific code into subdirectories.
Also, remove the remaining visual studio/WTL build project files.

## Motivation and Context
The formats directory was getting a bit unwieldy.

### CODE REVIEW

**Comment by sykhro** [comment]
Is github dying or the loader code disappeared?

**Comment by sykhro** [comment]
Btw, please add a `.git-blame-ignore-revs` file in the root of the repo containing the hashes of the commits with the mass-moving (mass-formatting) of files. This way, `git blame` doesn't become useless

**Review by sykhro — CHANGES_REQUESTED** [review]
See comments in PR

**Comment by mikelow** [comment]
Interesting, I didn't know about .git-blame-ignore-revs. I rewrote the commits and added an ignore for the mass move of format code into subdirectories

**Review by sykhro — APPROVED** [review]
LGTM, i will try to look into the forgotten macos error this week

**Comment by mikelow** [comment]
Awesome, that would be great!

I did some more testing on the Intel linker error issue and posted about it here: https://github.com/vgmtrans/vgmtrans/pull/436#issuecomment-2041683025

**Pull request merged**
