### PR TITLE
Remove the old Menu macros and WTL headers

### PR DESCRIPTION
**Pull request by mikelow**
They're all unused now that the WTL version is out.

### CODE REVIEW

**Comment by sykhro** [comment]
Could you also remove [dxAug07](https://github.com/vgmtrans/vgmtrans/tree/master/lib/dxAug07)?

**Review by sykhro — CHANGES_REQUESTED** [review]
We also have [dxAug07](https://github.com/vgmtrans/vgmtrans/tree/master/lib/dxAug07) which is now unused and needs removal

**Comment by mikelow** [comment]
Updated. Happy to get rid of it.

**Review by sykhro — APPROVED** [review]
That should be everything then

**Pull request merged**
