### PR TITLE
Fix FileNameMatcher and VirtFile::extension()

### PR DESCRIPTION
**Pull request by mikelow**
A couple issues addressed here:
- FileNameMatcher never sets the id for any of its file types, and is therefore totally broken. 
- VirtFile::extension() returns the extension of its parent raw file by default. This is undesirable, as we would usually prefer to get the extension of the filename of the VirtFile. For example, when extracting a psf2, the SonyPS2 scanner needs to know the extension of the sample collection file.

I've fixed FileNameMatcher and reversed the VirtFile::extension() logic so that it returns the VirtFile name extension first, and if none exists, the parent RawFile's extension.

This fixes detection of SonyPS2 collections.

## How Has This Been Tested?
I tested that every format is still detected correctly.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by sykhro — APPROVED** [review]
Sounds reasonable. I would like to remove the Raw/Virt distinction eventually and use memory-mapped files. I think I had that in my branch?

**Comment by mikelow** [comment]
> Sounds reasonable. I would like to remove the Raw/Virt distinction eventually and use memory-mapped files. I think I had that in my branch?

I think I pulled in your work, but correct me if I missed something. The code uses [mio](https://github.com/vimpunk/mio) for memory mapping. RawFile was made an abstract class with, DiskFile and VirtFile its non-abstract implementations.

**Comment by sykhro** [comment]
> > Sounds reasonable. I would like to remove the Raw/Virt distinction eventually and use memory-mapped files. I think I had that in my branch?
> 
> I think I pulled in your work, but correct me if I missed something. The code uses [mio](https://github.com/vimpunk/mio) for memory mapping. RawFile was made an abstract class, with DiskFile and VirtFile its non-abstract implementations.

Oh yes I remember this, I get the feeling I might never have pushed the refactor where I abstracted both of those away

**Comment by mikelow** [comment]
> Oh yes I remember this, I get the feeling I might never have pushed the refactor where I abstracted both of those away

Oh dang. Hopefully you didn't lose the work. If you're able to push it in some form, I'll gladly work on integrating it.

**Pull request merged**
