### PR TITLE
Update .clang-format, update VGMRoot fields

### PR DESCRIPTION
**Pull request by mikelow**
Consider this dipping a toe in the water for code reformatting.

There aren't actually that many changes here:

- Updated .clang-format
    - Removed `BasedOnStyle: Google`
    - Added: `BreakBeforeBraces: WebKit` and `ReferenceAlignment: Left`
- Renamed VGMRoot's vRawFile, vVGMFile, vVGMColl to m_rawfiles, m_vgmfiles, m_vgmcolls
- Made the above fields private and created getter functions: rawFiles(), vgmFiles(), vgmColls()
- Renamed pRoot to s_root
- Applied formatting to Root.h and Root.cpp to test the waters.

UPDATE:
I also needed to update CLIVGMRoot slightly. It was clearing the root vgmfile list, which is no longer possible as the getter returns a const and the field itself is private (but also, it was kind of a hack approach in the first place).

## Description

The `BreakBeforeBraces: WebKit` rule just adds a new line before the opening brace of a function, ie:
```
void myFunc()
{
  ...
}
```

instead of:
```
void myFunc() {
  ...
}
```

I went with this since it seems very common, but I don't feel strongly about it. The clang format style option doc is [here](https://clang.llvm.org/docs/ClangFormatStyleOptions.html).

I was tempted to use `BasedOnStyle: WebKit', but it resulted in some minor formatting issues that I didn't know how to override, like empty braces being separated with a space (`{ }` instead of `{}`), and putting the `= 0` of a multiline abstract method declaration on its own line. 🤷‍♂️ I'm concerned that we might lose good baseline rules by not using a BasedOnStyle definition.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code cleanup

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by sykhro** [comment]
> I went with this since it seems very common, but I don't feel strongly about it.

Since we neither feel strongly about anything, at this point it's probably better to use a `clang-format` style that ends up making the smallest amount of changes to the existing code to avoid losing too much in `git blame`. `clang-power-tools` offers a `clang-format` detector, you feed it a bunch of source files and it spits out a `.clang-format`.

Also, commits that do nothing but rename variables should be added to `.git-blame-ignore-revs` too

**Review by sykhro — CHANGES_REQUESTED** [review]
See PR comment

**Comment by mikelow** [comment]
> Since we neither feel strongly about anything, at this point it's probably better to use a clang-format style that ends up making the smallest amount of changes to the existing code to avoid losing too much in git blame. clang-power-tools offers a clang-format detector, you feed it a bunch of source files and it spits out a .clang-format.

I'm fine with making minimal changes. Granted, the variable, parameter, and function naming conventions alone will spur a lot of change. The one style rule I feel strongly about - and it's an oversight I didn't bring it up before - is left-aligning pointers and references. ie:

`int* myVar` over `int *myVar`.

I'm hoping you either agree with this or don't feel strongly on it 🤞. Oddly, our .clang-format file specified left-aligned pointers before this PR, but the line `BasedOnStyle: Google` somehow overrode it.

Changing all the files to conform to any new style guide is not a high priority in my view, though I wouldn't see it as a bad thing.

> Also, commits that do nothing but rename variables should be added to .git-blame-ignore-revs too

What about when we're adding getter functions? Same principle?

**Comment by sykhro** [comment]
> I'm hoping you either agree with this or don't feel strongly on it 🤞

I really don't mind what the code looks like as long as I can press ctrl+s and autoformatting takes care of it :)

> What about when we're adding getter functions? Same principle?

Adding getters shouldn't alter semantics but sometimes it does in unexpected ways. I would keep those commits

**Comment by sykhro** [comment]
The style detector came up with this btw:
```
BasedOnStyle: Google
AccessModifierOffset: -2
AlignAfterOpenBracket: DontAlign
AlignOperands: DontAlign
AllowAllArgumentsOnNextLine: false
AllowAllConstructorInitializersOnNextLine: false
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: Never
AlwaysBreakAfterReturnType: All
BinPackArguments: false
BinPackParameters: false
BreakBeforeBinaryOperators: NonAssignment
BreakConstructorInitializersBeforeComma: true
BreakConstructorInitializers: AfterColon
ColumnLimit: 200
ConstructorInitializerAllOnOneLineOrOnePerLine: false
ContinuationIndentWidth: 2
Cpp11BracedListStyle: false
EmptyLineBeforeAccessModifier: Leave
FixNamespaceComments: false
IncludeBlocks: Preserve
KeepEmptyLinesAtTheStartOfBlocks: true
MaxEmptyLinesToKeep: 3
ReflowComments: false
SortIncludes: false
SpaceBeforeCpp11BracedList: true
SpaceBeforeCtorInitializerColon: false
SpaceBeforeInheritanceColon: false
SpaceInEmptyBlock: true
SpacesBeforeTrailingComments: 3
```

doesn't look too minimal though /shrug, we can keep your config then

**Comment by mikelow** [comment]
> doesn't look too minimal though /shrug, we can keep your config then

It's still shorter than what we currently have. I agree it we should strive for a set of rules that minimize change we deem unimportant.

**Comment by sykhro** [comment]
> > doesn't look too minimal though /shrug, we can keep your config then
> 
> It's still shorter than what we currently have. I agree that we should strive for a set of rules that minimize change we deem unimportant.

It's a double-edged sword. Since clang-format isn't stable, the more options you have the less likely it is for updates in the future to change what the formatting looks like when new options are added or modified

**Comment by mikelow** [comment]
I've created a [separate PR](https://github.com/vgmtrans/vgmtrans/pull/491) that changes the root field names and adds the getter methods, but removes the .clang-format stuff for now. We can come back to that later, and it should be a separate change anyway.

**Pull request closed without merging**
